# Auto-generated by Terraform — do not edit manually.
# Regenerate by running: terraform apply

# ─── Database (Akamai/Linode Managed PostgreSQL) ──────────────────────────────
DB_HOST=${db_host}
DB_PORT=${db_port}
DB_NAME=${db_name}
DB_USER=${db_user}
DB_PASSWORD=<run setup_db.py --write-env to fill this in>
DB_SSL=require

# ─── JWT Auth ─────────────────────────────────────────────────────────────────
JWT_SECRET=${jwt_secret}
JWT_ALGORITHM=HS256
JWT_EXPIRE_MINUTES=${jwt_expire_minutes}

# ─── Linode API ───────────────────────────────────────────────────────────────
LINODE_API_BASE=https://api.linode.com/v4
REFRESH_API_SECRET=${refresh_api_secret}

# ─── Token Encryption ─────────────────────────────────────────────────────────
TOKEN_ENCRYPTION_KEY=${token_encryption_key}

# ─── CORS ─────────────────────────────────────────────────────────────────────
CORS_ORIGINS=${cors_origins}

# ─── Security ─────────────────────────────────────────────────────────────────
ALLOW_REGISTRATION=${allow_registration}
TRUSTED_PROXY_COUNT=${trusted_proxy_count}
